default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: com214_web_development_development
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  sslmode: disable

test:
  <<: *default
  database: com214_web_development_test
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  sslmode: disable

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>